spring:
  security:
    user:
      name: root
      password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.174.150/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
    #不返回值为null的属性
    #可给属性赋初始值返回[]
  redis:
    host: 192.168.174.150
    port: 6379
    password:
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
server:
  servlet:
    context-path: /sell
  port: 8080
wechat:
  mpAppId: wxf7a389ceb3300fd5
  mpAppSecret: 3b655b2a20f855185b956b96576a7424
  openAppId:
  openAppSecret:
  mchId: 111111111
  mchKey: 1
  keyPath: 1
  notifyUrl: http://myapp.utools.club/sell/pay/notify
  templateId:
    test: 5Nif4MjOEyZWDDf5z_oRygHqe6VPHAm9U8g88lkvulA
    test1:
    orderStatus:
project-url:
  wechatMpAuthorize: https://myapp.utools.club
  wechatOpenAuthorize: https://myapp.utools.club
  sell: https://myapp.utools.club

